export const ON_SIGN_UP_INPUT_CHANGE = 'ON_SIGN_UP_INPUT_CHANGE';
export const ON_LOGIN_INPUT_CHANGE = 'ON_LOGIN_INPUT_CHANGE';
export const POST_SIGN_UP = 'POST_SIGN_UP';
export const POST_LOGIN_DATA = 'POST_LOGIN_DATA';
